remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: María Batz de León - Desarrollo de Software
description: Compila muestras de los trabajos recientes.

